name: Build & Publish Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on:  [self-hosted, Linux, btg-ws]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: registry.uw.systems
          username: ${{ secrets.DOCKER_REGISTRY_UW_SYSTEMS_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_UW_SYSTEMS_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: registry.uw.systems/btg-build/docker-wix:latest
